events {
    worker_connections 1024;
}

http {
    # Define a shared memory zone for tracking IP addresses
    # 10m (10 megabytes) can hold about 160,000 states. 
    # We restrict traffic to 10 requests per second (10r/s)
    limit_req_zone $binary_remote_addr zone=api_limit_zone:50m rate=100000r/s;

    # Custom log format to see rate limit status easily
    log_format custom_format '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "limit_status:$limit_req_status"';

    server {
        listen 80;
        access_log /var/log/nginx/access.log custom_format;

        location /api/ {
            # Apply the rate limiting zone here
            # burst=5 allows temporary bursts of up to 5 requests
            # nodelay ensures requests within the burst limit don't experience artificial latency
            limit_req zone=api_limit_zone burst=5 nodelay;

            # Custom header to explicitly show which NGINX node processed it
            add_header X-Processed-By "Layer1-Local-NGINX" always;

            # Forward clean traffic to Layer 3 (Mock Backend Service)
            proxy_pass http://backend-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /laravel {
            # Apply the rate limiting zone here
            # burst=5 allows temporary bursts of up to 5 requests
            # nodelay ensures requests within the burst limit don't experience artificial latency
            limit_req zone=api_limit_zone burst=5 nodelay;

            # Custom header to explicitly show which NGINX node processed it
            add_header X-Processed-By "Layer1-Local-NGINX" always;

            # Rewrite to remove /laravel from the request path before proxying
            rewrite ^/laravel/?(.*)$ /$1 break;

            # Forward clean traffic to Layer 3 (Mock Backend Service)
            proxy_pass http://laravel-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
